// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ecmdiydvpzywecggggzi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVjbWRpeWR2cHp5d2VjZ2dnZ3ppIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk2OTc5NzYsImV4cCI6MjA2NTI3Mzk3Nn0.7KzhHaMB5xtama2kIdknz2pfpflVTbTWJwamwPFMp7c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);